Added Button component
codex-team/hawk.garage.react pull request #22
Opened 2022-08-07 21:23 UTC by slaveeks

resolves #10

2022-08-07 21:25 UTC, slaveeks commented
Some colors in styles are wrong, because i did't use functions like color-mod and etc.

2022-08-08 11:54 UTC, GeekaN2 requested changes

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.module.pcss
> +    padding: 12px 15px;
Все переменные нужно стащить из дизайн-системы.
`padding: var(--space-s) var(--space-m);`

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.module.pcss
> +    border: solid 1px #dbe6ff19;
Включая цвета. Прозрачный замени на непрозрачный, вроде уже есть в системе нужный цвет

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.module.pcss
> +    color: #dbe6ff !important;
Не используй important, если хочешь перебить класс, используй вложенные селекторы. important это зло

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.module.pcss
> +    background-size: 56px 56px;
Все переменные связанные с кнопкой надо вынести в дизайн систему типа такого:
```
--button-view-action-typo-color-checked-base: var(--color-button-primary-text);
--button-view-action-typo-color-checked-hovered: var(--color-button-primary-text);
--button-view-action-border-color-focused: var(--color-control-focus-base);
--button-view-action-fill-color-disabled: var(--color-control-disabled-fill);
```

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.tsx
> +  buttonSize?: ButtonSize | ButtonSize.General,
Комментарии повторяющие описание пропа бесполезны. Итак понятно, что этот проп делает. Добавляй комментарии тогда, которые могут помочь понять, что вообще происходит.
И лучше переименовать `buttonsSize` в `size`, иначе тавтология получается, можно еще размеры заменить на `'s' | 'm' | 'l'`, как в Text сделали, смотрится лучше

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.tsx
> +  styleType?: ButtonStyle | ButtonStyle.Submit,
Давай переименуем во view или type, например.
`submit -> action`, submit это частный случай действия, а у нас действий есть много
`secondary -> default`, это не самая часто испольуземая кнопка у нас помимо submit? Го её в default

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.tsx
> +
Скругление должно зависеть от размера кнопки, лишний проп
У нас не будет различных кнопок, одни со скругление, другие без.

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.tsx
> +                         ${props.isLoading ? styles.isLoading : ''}` }>
Посмотри как используется classnames в Text и сделай также.

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.tsx
> +      }
Лучше сделать как ReactNode или вообще в виде коллбека типа `(iconClassName: string) => React.ReactNode`. Нам будут передавать функцию, мы вызывать её, передавая нужный нам класс, центрирующий иконку по вертикали + выставляющий отступы в зависимости от размера

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.tsx
> +      }
У многих иконки собираются лоадерами, поэтому img вряд ли подойдет

2022-08-08 11:54 UTC, GeekaN2 commented on src/commons/components/Button/Button.stories.tsx
> +};
Слишком много сторей. Сделай одну дефолтную сторю, она же Playground, где можно поиграться. И еще одну с таблицей свойств, например по горизонтали size, по вертикали все остальное.

2022-08-08 12:10 UTC, ilyamore88 requested changes

2022-08-08 12:10 UTC, ilyamore88 commented on src/commons/components/Button/Button.stories.tsx
> +const Template: ComponentStory<typeof Button> = (args) => <Button
Let's use props here
```suggestion
const Template: ComponentStory<typeof Button> = (props) => <Button
```

2022-08-08 12:10 UTC, ilyamore88 commented on src/commons/components/Button/Button.stories.tsx
> +};
If you create a Default story here, you don't need to provide args. Storybook will parse props and will show you controls.

2022-08-08 12:10 UTC, ilyamore88 commented on src/commons/components/Button/Button.tsx
> +  isDisabled?: boolean,
Let's name these props in HTML style: `disabled`, `loading` etc.

2022-08-08 12:10 UTC, ilyamore88 commented on src/commons/components/Button/Button.tsx
> +const Button: React.FC<Props> = ({ ...props }) => {
You can take props for styles. `{ disabled, loading, ...props}`. You don't need to write `props.` every time.

2022-08-08 12:10 UTC, ilyamore88 commented on src/commons/components/Button/Button.tsx
> +      <div className={styles.text}>
Do you need this element? I think it's redundant.

2022-08-08 12:41 UTC, slaveeks commented on src/commons/components/Button/Button.module.pcss
> +    padding: 12px 15px;
А если у меня значения, которых нет в дизайн системе, то примерные поставить, или как?

2022-08-08 12:43 UTC, GeekaN2 commented on src/commons/components/Button/Button.module.pcss
> +    padding: 12px 15px;
Добавь в дизайн систему переменную, я попозже с неймингом всего и вся разбирусь, нужно гайдланы составить

2022-08-08 12:52 UTC, ilyamore88 commented on src/commons/components/Button/Button.module.pcss
> +    padding: 12px 15px;
Но также сам посмотри по поводу новых размеров

2022-08-08 12:53 UTC, ilyamore88 commented on src/commons/components/Button/Button.module.pcss
> +    padding: 12px 15px;
Типа точно ли нам нужен 15px

2022-08-08 12:53 UTC, ilyamore88 commented on src/commons/components/Button/Button.module.pcss
> +    padding: 12px 15px;
Если у нас уже есть 14 или 16

2022-08-08 12:53 UTC, ilyamore88 commented on src/commons/components/Button/Button.module.pcss
> +    padding: 12px 15px;
Нужно постараться добиться одинаковых отступов везде, даже если в дизайне какой-то рандом

2022-08-08 16:07 UTC, GeekaN2 commented on src/commons/themes/root.css
> +  --space-xss: 6px;
Ты точно уверен, что 6 пикселей тебе нужен размер?
Я бы мелкую кнопку больше сделал, она какая-то сдавленная
Увеличил бы `padding: var(--space-s) var(--space-m);`

2022-08-08 19:41 UTC, ilyamore88 commented on src/commons/components/Button/Button.stories.tsx
> +    title: 'Example/Button',
@GeekaN2 кнопка это Input? Тогда лучше поместить в Input/... вместо Example

2022-08-08 19:42 UTC, ilyamore88 commented on src/commons/components/Button/Button.tsx
> +                         loading ? styles.loading : '')}>
Можно в cn передать объект. типа 
```
cn({
  [style.submit]: submit
})
```
Тогда класс будет применён только при true справа

2022-08-08 19:43 UTC, ilyamore88 commented on src/commons/components/Button/Button.tsx
> +                         loading ? styles.loading : '')}>
Объект может идти любым аргументом, то есть там можно передать (default, {...}, className)

2022-08-08 19:46 UTC, ilyamore88 commented on src/commons/themes/root-colors-dark.css
> +  --color-bg-button-secondary: #50638c;
Отдели плиз пустой строкой от цветов фона приложения

2022-08-09 15:54 UTC, ilyamore88 approved these changes

2022-08-11 08:59 UTC, GeekaN2 approved these changes
Пока норм, дальше будем улучшать

2022-08-11 09:02 UTC, merged