Added checkbox component
codex-team/hawk.garage.react pull request #35
Opened 2022-09-15 21:43 UTC by slaveeks

resolves #19

2022-09-17 14:45 UTC, ilyamore88 requested changes

2022-09-17 14:45 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +           }}
Вынеси это плиз в именованную функцию

2022-09-17 14:45 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +  const [checkedState, setChecked] = React.useState(checked);
Должен ли чекбокс иметь внутреннее состояние? Ведь ты можешь просто вызывать onClick(!checked)

2022-09-17 14:45 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +  const [checkedState, setChecked] = React.useState(checked);
И без внутреннего состояния тебе не надо будет использовать useEffect

2022-09-17 14:45 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +const Checkbox: React.FC<Props> = ({ disabled, checked, onClick,...props }) => {
...props нигде не используется

2022-09-17 14:45 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.module.css
> +.disabled {
Этот класс где-то добавляется? Вообще есть мысль привязаться к атрибуту disabled. И не плодить тут класс. Можешь попробовать такое сделать? Как оно будет работать

2022-09-17 14:45 UTC, ilyamore88 commented on public/tick.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="15" height="10" viewBox="0 0 15 10" fill="white">
Этот файл должен лежать в src, не в public в корне. Vite должен зарезолвить путь до него

2022-09-17 14:45 UTC, ilyamore88 commented on public/tick.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="15" height="10" viewBox="0 0 15 10" fill="white">
И ещё я бы сделал у него fill="currentColor", чтобы можно было выставлять цвет через CSS

2022-09-17 14:45 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +const Checkbox: React.FC<Props> = ({ disabled, checked, onClick,...props }) => {
Ещё есть прикольная штука для onClick, ты можешь погуглить lodash.noop. Это типа пустая функция. С ней тебе не придётся проверять, получаешь ли ты коллбек. Просто тут можно написать onClick = noop

2022-09-17 16:47 UTC, slaveeks commented on public/tick.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="15" height="10" viewBox="0 0 15 10" fill="white">
Я сделал currentColor, но когда я в css прописываю color, цвет иконки не меняется, я по разному пытался, почему-то не выходит, возможно, с использованием иконки в content так не работает?

2022-09-17 16:51 UTC, slaveeks commented on src/commons/components/Checkbox/Checkbox.tsx
> +  const [checkedState, setChecked] = React.useState(checked);
<img width="265" alt="image" src="https://user-images.githubusercontent.com/81693471/190867723-04dc9a16-d735-4474-9335-86b0ad23ecfa.png">

я вот так прописал, но почему-то, если в пропсах передавать конкретное значение true/false, состояние не меняется

2022-09-19 08:58 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +  const [checkedState, setChecked] = React.useState(checked);
Давай только стрелочную функцию тут

2022-09-19 09:01 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +  const [checkedState, setChecked] = React.useState(checked);
Не меняется из-за потока данных. В реакте пропсы менять нельзя в дочернем компоненте. Для этого ты передаёшь в пропсах коллбек onClick. Можешь его назвать как-то более подходяще типа onChange(!checked). Тогда будет что-то вроде:

```js
const onClick = () => {
  props.onChange(!checked);
};
```

2022-09-19 09:02 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +  const [checkedState, setChecked] = React.useState(checked);
onClick ты вешаешь на <input>, а в родительском компоненте будет что-то вроде:
```jsx
<Checkbox 
  onChange{ (newValue) => console.log(newValue) }
/>
```

2022-09-19 09:04 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +  const [checkedState, setChecked] = React.useState(checked);
https://reactjs.org/docs/forms.html#controlled-components

2022-09-19 13:17 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +      </label>
Нельзя вставить этот tick внутрь инпута? Типа `<input><Tick/></input>`

2022-09-19 13:18 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +           id={'cb'}
И id у тебя не уникальный. Я бы попробовал добавить Tick без лейбла пока что

2022-09-19 13:20 UTC, slaveeks commented on src/commons/components/Checkbox/Checkbox.tsx
> +           id={'cb'}
У меня label вообще выполняет роль чекбокса, я просто воспользовался альтернативой :before или :after, чтобы можно было расположить иконку внутрь зеленого квадрата для совместной анимации

2022-09-19 14:57 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.module.css
> +    &.disabled {
```suggestion
    &:disabled {
```

2022-09-19 14:57 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +                      })}
Ты можешь использовать псевдокласс для этого `:disabled`

2022-09-19 14:57 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +      <input type={'checkbox'}
Просто добавь сюда onClick второй. Чисто теоретически у тебя он должен срабатывать тогда только при использовании a11y при фокусе

2022-09-19 14:58 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +    !disabled ? onChange(!checked) : null;
Лучше запиши это нормальным if (!disabled) ...

2022-09-19 15:30 UTC, slaveeks commented on src/commons/components/Checkbox/Checkbox.tsx
> +                      })}
Я точно могу использовать псевдокласс disabled для div? Просто мне кажется, что так нельзя

2022-09-20 08:48 UTC, ilyamore88 commented on src/commons/components/Checkbox/Checkbox.tsx
> +                      })}
Ааа, точно. Тогда не можешь, да)

2022-09-21 14:52 UTC, ilyamore88 approved these changes

2022-09-21 14:54 UTC, GeekaN2 commented on src/commons/components/Checkbox/Checkbox.module.css
> +    padding: 3px;
Переменную сюда мне

2022-09-21 14:54 UTC, GeekaN2 approved these changes

2022-09-21 15:01 UTC, merged