Created login page
codex-team/hawk.garage.react pull request #36
Opened 2022-09-22 00:52 UTC by slaveeks

resolves #26

2022-09-22 17:09 UTC, ilyamore88 commented on src/App.tsx
> +    <div className={cn('hds-root-colors-dark', 'hds-root-colors-light', 'hds-root', styles.app)}>
Тема должна быть одна. Смысл в том, что при переключении классов dark/light ты получаешь доступ к разным значениям одних и тех же переменных

2022-09-22 17:10 UTC, ilyamore88 commented on src/App.tsx
> +    <div className={cn('hds-root-colors-dark', 'hds-root-colors-light', 'hds-root', styles.app)}>
Оставь пока только dark. Ну и лучше помнить порядок и hds-root в самое начало поставить

2022-09-23 09:00 UTC, ilyamore88 reviewed
Добавь плиз стори для delimiter, fieldset и страницы логина

2022-09-23 09:00 UTC, ilyamore88 commented on src/pages/Login/Login.module.css
> +    a:hover {
Занеси это в a { &:hover {} }

2022-09-23 09:00 UTC, ilyamore88 commented on src/pages/Login/Login.tsx
> +        <Fieldset className={styles.fieldset} label={'email address'} type={'email'} name={'email'} placeholder={'name@best-team.com'}/>
Добавь плиз autocomplete

2022-09-23 09:00 UTC, ilyamore88 commented on src/commons/components/Delimiter/Delimiter.module.css
> +    background: var(--color-text-primary);
Меня смущает зависимость от текста. И магическая прозрачность в 11 процентов. Можешь взять чистый цвет без opacity? И сделать под это переменную

2022-09-23 12:46 UTC, ilyamore88 commented on src/commons/layouts/auth/base/Base.module.css
> +    a:hover {
Тут тоже не заметил, занеси плиз в &:hover

2022-09-23 12:46 UTC, ilyamore88 commented on src/commons/themes/root-colors-dark.css
> +  --color-delimiter: rgb(67, 71, 85)
Можно через # 😬?

2022-09-23 13:16 UTC, ilyamore88 approved these changes
Лайк

2022-09-27 14:22 UTC, GeekaN2 commented on src/App.tsx
>            <div>Click on the link</div>
Shiet, нам нужны переводы

2022-09-27 14:23 UTC, GeekaN2 commented on src/commons/layouts/auth/base/Base.module.css
> +    font-size: 30px;
Font-sizes have to be in our design-system

2022-09-27 14:24 UTC, ilyamore88 commented on src/App.tsx
>            <div>Click on the link</div>
Пока нет

2022-09-27 14:24 UTC, GeekaN2 commented on src/commons/layouts/auth/base/Base.module.css
> +    margin: 20px 0 25px;
Design-system. Добавить --space-<n>-xl с промежутком в 4px, чтобы для больших отступов тоже были

2022-09-27 14:24 UTC, GeekaN2 commented on src/commons/layouts/auth/base/Base.tsx
> +      <Text weight={"bold"} size={"m"} className={styles.title}>Hawk</Text>
Можно делать `weight="bold"` бтв

2022-09-27 14:26 UTC, GeekaN2 requested changes
Gimme some styles from the design system and I approve it

2022-09-28 12:40 UTC, GeekaN2 approved these changes

2022-09-28 12:41 UTC, merged