feat(auth): add Sign Up page
codex-team/hawk.garage.react pull request #37
Opened 2022-09-24 14:38 UTC by ilyamore88

2022-09-24 18:01 UTC, slaveeks commented on src/commons/layouts/auth/base/Base.module.css
> +.formContainer {
Поменяй еще тут

<img width="237" alt="image" src="https://user-images.githubusercontent.com/81693471/192112239-153218ee-2733-458b-b80f-bf8ca4c5de84.png">

2022-09-24 18:49 UTC, slaveeks approved these changes

2022-09-27 14:27 UTC, GeekaN2 commented on src/commons/layouts/auth/base/Base.module.css
> +    @media (max-width: 980px) {
Я бы размеры экранов в переменные вынес, они же одни и те же для всего будут. По-любому копипаста начнется, а не хочется

2022-09-27 14:27 UTC, GeekaN2 commented on src/pages/SignUp/SignUp.module.css
> +    margin-bottom: 20px;
🦄

2022-09-27 14:29 UTC, GeekaN2 commented on .storybook/assets/global.css
> +    padding: 0 !important;
Do not use `!important`. wtf, use nesting if you want to have more priority on the selector

2022-09-27 14:31 UTC, GeekaN2 commented on .storybook/assets/global.css
> +    padding: 0 !important;
It's `global.css` so forget my words

2022-09-27 14:31 UTC, GeekaN2 requested changes
`margin-bottom: 20px;` 🦄

2022-09-29 13:25 UTC, GeekaN2 approved these changes

2022-09-29 13:26 UTC, merged